name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: cerit.io
          username: xadler
          password: ${{ secrets.HARBOR_KEY }}

    
     # - uses: actions/checkout@v4
     # - name: Build the Docker image
     #   run: docker build . --file Dockerfile --tag archaeo-vault-drupal:$(date +%s)

      -
        uses: docker/build-push-action@v6
        name: Build and push
        with:
          tags: archaeo-vault-drupal:latest
          file: Dockerfile
          push: true
          
