name: Automatic image build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to assign to built image"
        default: "git-action-test"
        required: true
      branch_conf:
        description: "Branch or tag of config repo"
        default: "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: cerit.io
          username: xadler
          password: ${{ secrets.HARBOR_KEY }}

      -
        uses: docker/build-push-action@v7
        name: Build and push
        with:
          file: Dockerfile
          push: true
          tags: "cerit.io/xadler/archaeo-vault-drupal:${{ inputs.tag }}"
          build-args: BRANCH_CONF=${{ inputs.branch_conf }}

