name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: cerit.io
          username: xadler
          password: ${{ secrets.HARBOR_KEY }}

      -
        uses: docker/build-push-action@v6
        name: Build and push
        with:
          tags: cerit.io/xadler/archaeo-vault-drupal:git-action-test
          file: Dockerfile
          push: true
          
