name: Automatic image build


on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to assign to built image"
        default: "git-action-test"
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: cerit.io
          username: xadler
          password: ${{ secrets.HARBOR_KEY }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: "cerit.io/xadler/archaeo-vault-drupal:${{ inputs.tag }}"

      -
        uses: docker/build-push-action@v7
        name: Build and push
        with:
          file: Dockerfile
          push: true
          sbom: true
          tags: "cerit.io/xadler/archaeo-vault-drupal:${{ inputs.tag }}"
          #build-args: BRANCH_CONF=test

